[package]
name = "oh-no"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1
package."*" = { opt-level = 3 }

[dependencies]
comfy-table = "7.0.1"

[dependencies.bevy]
version = "0.11"
